[package]
name = "clurd"
version = "0.1.0"
license = "ISC"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.0.3"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
json = "0.12.4"


